language: haskell

before_script:
  - mv config/settings-dummy.yml config/settings.yml
  - git submodule update --init --recursive
  - cd static/css && cp ../../bootstrap-select/bootstrap-select.min.css .
  - cd ../js && cp ../../bootstrap-select/bootstrap-select.min.js .
  - cd ../../

script:
  - cabal install --only-dependencies --dry-run
  - cabal configure && cabal build

before_install:
  - export PATH=/usr/lib/ghc/bin:~/.cabal/bin:$PATH # for hsc2hs
  - cabal install happy
  - cabal install alex
  - cabal install c2hs

install:
  - cabal sandbox init
  - cabal install --only-dependencies
