language: haskell

before_script:
  - mv config/settings-dummy.yml config/settings.yml
  - git submodule update --init --recursive
  - cd static/css && ln -s ../../bootstrap-select/bootstrap-select.min.css .
  - cd ../js && ln -s ../../bootstrap-select/bootstrap-select.min.js .
  - cd ../../

script:
  - ~/.cabal/bin/cabal-dev install --only-dependencies --dry-run
  - ~/.cabal/bin/cabal-dev configure && ~/.cabal/bin/cabal-dev build

install:
  - cabal install cabal-dev
  - ~/.cabal/bin/cabal-dev install --only-dependencies
