language: haskell

before_script:
  - mv config/settings-dummy.yml config/settings.yml
  - git submodule update --init --recursive
  - cd static/css && cp ../../bootstrap-select/bootstrap-select.min.css .
  - cd ../js && cp ../../bootstrap-select/bootstrap-select.min.js .
  - cd ../../

before_install:
  - export PATH=/usr/lib/ghc/bin:~/.cabal/bin:$PATH # for alex
  - cabal install alex

script:
  - cabal configure --enable-tests && cabal build
  - cabal test

install:
  - cabal sandbox init
  - cabal install --only-dependencies --enable-tests
