language: haskell

env:
  - CABALVER=1.22 GHCVER=7.10.2

before_script:
  - mv config/settings-dummy.yml config/settings.yml
  - git submodule update --init --recursive
  - cd static/css && cp ../../bootstrap-select/bootstrap-select.min.css .
  - cd ../js && cp ../../bootstrap-select/bootstrap-select.min.js .
  - cd ../../

before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install -y -qq cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.20/bin:$PATH
  - export PATH=~/.cabal/bin:$PATH # for alex
  - cabal update
  - cabal install alex happy
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack --skip-ghc-check setup
  - stack +RTS -N2 -RTS --no-terminal build

script:
  - stack +RTS -N2 -RTS --no-terminal test
