language: haskell

env:
  - GHCVER=7.6.3
  - GHCVER=7.8.3

before_script:
  - mv config/settings-dummy.yml config/settings.yml
  - git submodule update --init --recursive
  - cd static/css && cp ../../bootstrap-select/bootstrap-select.min.css .
  - cd ../js && cp ../../bootstrap-select/bootstrap-select.min.js .
  - cd ../../

before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install -y -qq cabal-install-1.18 ghc-$GHCVER alex
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.18/bin:$PATH
  - export PATH=~/.cabal/bin:$PATH # for alex
  - cabal update
  - cabal install alex happy

script:
  - cabal configure --enable-tests && cabal build
  - cabal test

install:
  - cabal sandbox init
  - cabal install --only-dependencies --enable-tests
