language: haskell

before_script:
  - mv config/settings-dummy.yml config/settings.yml

script:
  - cabal configure && cabal build

install:
  - cabal install --dry-run --only-dependencies
  - cabal install --only-dependencies
