resolver: lts-8.5

packages:
  - location: .
  # - location: deploy/

extra-deps:
  - friendly-time-0.4
  - yesod-markdown-0.11.4
  - yesod-paginator-0.11.0
  - yesod-default-1.2.0
  - hsc2hs-0.68.1
  - load-env-0.1.1

flags: {}

extra-package-dbs: []
