Hello: Hello
## Handler
#Foundation.hs
NotAnAdmin: You have not permission to access this page.
#Image.hs
FileSaved: File saved
FileDeleted: File has been deleted.
CannotRegisterImage: You cannot register same filename image!!
SomethingWentWrong: Something went wrong
#Admin.hs
AdminPageTitle: Admin Page
PostArticleFailure: Please correct your entry form
PostArticleCommentSuccess: Your comment was posted
PostArticleCommentFailure: Error occurred
ArticleSomethingWentWrong: Something went wrong
ArticleDelete: Delete
DeleteOneselfError: You cannot delete yourself!!
ArticleEdit: Edit Blog
#Article.hs
ArticleCommentPost: Your comment was posted
ArticleErrorOccurred: Error occurred
ArticleArchive: Article Archive
#Blog.hs
TaggedArticle: Tagged Article
#User.hs
UserSetting: Settings
#About.hs
AboutTitle: About
## Helper
#Form.hs
FormArticleTitle: Title
FormArticleContent: Content
FormArticleSlug: Slug
FormArticleTag: Tag
FormCommentName: Name
FormCommentContent: Comment
#Image.hs
FormFileUpload: Upload file
FormFileDescription: file description
#UserForm.hs
FormUserName: Screen Name