stanzas:
    - type: webapp
      exec: ../dist/build/Ahblog/Ahblog
      args:
          - production
      host: localhost

# Use the following to automatically copy your bundle upon creation via `yesod
# keter`. Uses `scp` internally, so you can set it to a remote destination
# copy-to: user@host:/opt/keter/incoming

# Static file hosts. Keter handles the serving for you.
#static-hosts:
#    - host: static.<<HOST-NOT-SET>>
#      root: ../static # relative to config file, just like the executable

# however, the requests from nginx -> keter will not come to
# that hostname, so we need to tell keter to listen on something
# else as well
#extra-hosts:
#  - "127.0.0.1:8000"
