Default: &defaults
  database: Ahblog.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Ahblog_test.sqlite3
  <<: *defaults

Staging:
  database: Ahblog_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Ahblog_production.sqlite3
  poolsize: 100
  <<: *defaults
