Default: &defaults
  database: myproj.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: myproj_test.sqlite3
  <<: *defaults

Staging:
  database: myproj_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: myproj_production.sqlite3
  poolsize: 100
  <<: *defaults
